Creat the sign up page
202306-NEA-DZ-FEW/online-Therapist pull request #64
Opened 2023-10-23 17:35 UTC by Lilicod

This pull request introduces the signup page. Here's an overview of the changes:

**1. Responsive Design:**

**2. Multiple Signup Methods:**
Users can now sign up through three different methods:

- Email and Password
- Google
- Facebook

**3. User Profile Page:**
After successful signup, users can access their profile page, which displays their name and email address.

![Capture d’écran 2023-10-23 182510](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/cd021bcb-87f5-4579-970d-59d696a7e974)
![Capture d’écran 2023-10-23 182416](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/5cbb7e18-c9ff-4016-b60a-97a8518ff1c6)
![Capture d’écran 2023-10-23 182328](https://github.com/202306-NEA-DZ-FEW/online-Therapist/assets/88055548/1f5dd6ff-141e-4ea2-8418-0fe372b0ac58)

2023-10-23 22:13 UTC, dzc0d3r approved these changes
Amazing  Work :100: @Lilicod 

Thank You :1st_place_medal:

2023-10-23 22:30 UTC, M07am3dM approved these changes
Great work @Lilicod, well done.

2023-10-23 22:49 UTC, meryem08 approved these changes
Great work @Lilicod 👏👏

2023-10-23 23:10 UTC, dzc0d3r requested changes

2023-10-23 23:10 UTC, dzc0d3r commented on .husky/pre-commit
> +# npx lint-staged
@Lilicod 
Please don't forget to uncomment this line before merging 
```suggestion
 npx lint-staged
```

2023-10-24 14:02 UTC, HabchiSidAli commented
Nicely done @Lilicod!

2023-10-24 22:00 UTC, merged